### ISSUE TITLE
Autocomplete features that are missing.

### ISSUE THREAD

**Issue by winterwolf** [changnet/lua-tags#6]
Here is the list of snippets  which I used together with your extension because it doesn't provide autocomplete for simple things like `function`, `return` or `local`. It would be great if you add them to the standard functionality of your extension, because snippets behave very stupidly. They offer to insert themselves where they are not needed at all.

Thank you for your wonderful extension btw! I love it much more than emmylua, because it doesn't try to be smarter than me :D

```json
{
    "elif": {
        "body": "else if ${1:condition} then\n\t$0",
        "description": "elif",
        "prefix": "elif",
    },
    "for": {
        "body": "for ${1:index} = ${2:1}, ${3:10} do\n\t${0:print(index)}\nend",
        "description": "for index=1,10",
        "prefix": "for",
    },
    "fori": {
        "body": "for ${1:index}, ${2:value} in ipairs(${3:table_name}) do\n\t${0:print(index, value)}\nend",
        "description": "for index,value in ipairs()",
        "prefix": "fori",
    },
    "forp": {
        "body": "for ${1:key}, ${2:value} in pairs(${3:table_name}) do\n\t${0:print(key,value)}\nend",
        "description": "for key, value in pairs()",
        "prefix": "forp",
    },
    "function": {
        "body": "function ${1:function_name}($2)\n\t$0\nend",
        "description": "function",
        "prefix": "function",
    },
    "if": {
        "body": "if ${1:condition} then\n\t$0\nend",
        "description": "if",
        "prefix": "if",
    },
    "ifel": {
        "body": "if ${1:condition} then\n\t$2\nelse\n\t$0\nend",
        "description": "ifel",
        "prefix": "ifel",
    },
    "local": {
        "body": "local ${1:x} = ${0:1}",
        "description": "local x = 1",
        "prefix": "local",
    },
    "return": {
        "body": "return $1",
        "description": "return ...",
        "prefix": "return",
    }
}
```

**Comment by changnet** [comment]
What do you mean "because snippets behave very stupidly"？

Setting up custom snippets can be done at Visual Studio Code's menu File/Preferences/User Snippets. It should be the same putting them in extension.

Are they behave differently?

**Comment by changnet** [comment]
If you mean snippets do not show before other autocompletion, take a look at https://code.visualstudio.com/docs/editor/intellisense#_snippets-in-suggestions

and some discuss https://stackoverflow.com/questions/37863609/vs-code-intellisense-dont-suggest-snippet-at-first here.

**Comment by winterwolf** [comment]
@changnet let me show you example.

This is "smart" or "object-oriented" autocomplete from your beautiful extension:

![1](https://user-images.githubusercontent.com/42620439/99810794-e9813500-2b4c-11eb-9b63-021a7483f42a.png)

And this not very smart autocomplete from my snippets:

![2](https://user-images.githubusercontent.com/42620439/99810579-960ee700-2b4c-11eb-805e-fb2b9d43d7ea.png)

You see, stippets don't care about context. They suggests in any part of code, including comments.

I understand that your extension also can't provide perfect autocomplete (because lua is very flexible language)
but this is absolutely fine! If your hints just a bit "smarter" than default snippets, this is already cool!

**Comment by changnet** [comment]
Seems relate to https://github.com/Microsoft/vscode/issues/45164

If you have setting like this
```json
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": false
    }
```
then suggests shown inside comments, default is `"comments": false`

**Comment by winterwolf** [comment]
@changnet very strange. My "comments" field is false, but I still get these suggestions. Anyway, thank you for help and never mind, this is not important issue.

**Comment by changnet** [comment]
Check both "User" and "Workspace" setting，or manually set `"comments": true` in Workspace setting. I test both my extesion and MS's official typescript extension, can't reproduce your issue.

**Comment by winterwolf** [comment]
I tried true and false in both files. Nothing changes.

![screenshot-001](https://user-images.githubusercontent.com/42620439/99881284-80b7bc80-2c21-11eb-8120-7f38aeed91fa.png)

**Comment by winterwolf** [comment]
You know, I recently realized that the main advantage of snippets is their flexibility and the ability to customize as you like. It is possible that not everyone will be comfortable with hardcoded autocomplete, so I better close this issue. Your extension is good as is. Sorry for disturbing.
